services:
  db:
    container_name: starter-db
    image: mysql:8.0 # or latest:
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    init: true
  web:
    container_name: starter-web
    build: .
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - SELENIUM_DRIVER_URL=http://chromium:4444/wd/hub
    command: /bin/sh -c "wait-for-it.sh db:3306"
    volumes:
      - .:/webapp
      - bundle-data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    init: true
#   chromium:
#     image: seleniarm/standalone-chromium:latest
#     ports:
#       - 4444:4444
#   wait:
#     image: willwill/wait-for-it:latest
volumes:
  db-data:
  bundle-data:
